### ISSUE TITLE
No information on how to add EasyAdapter to you project

### ISSUE THREAD

**Issue by bartek-wesolowski** [MaksTuev/EasyAdapter#1]
I'd like to add EasyAdapter to my project, but I don't know how to do it without copying the code. Is it published to a Maven repository? Should it be used with JitPack? What's the latest version? You should add this information to readme.

**Comment by MaksTuev** [comment]
You can find this information here https://bitbucket.org/surfstudio/android-standard/wiki/Home  , but this documentation in Russian
