### ISSUE TITLE
Размещение на bintray

### ISSUE THREAD

**Issue by olegivo** [MaksTuev/EasyAdapter#3]
Здравствуйте! Я хотел бы поучаствовать и опубликовать форк вашего проекта в виде общедоступной библиотеки на bintray/jcenter. Это возможно? Есть ли какие-то ограничения по распространению, лицензии и т.д.? Либо посодействовать распространению.

**Comment by MaksTuev** [comment]
Здравствуйте. Спасибо за предложение, но этот проект является только примером. Артефакт с EasyAdapter был недавно опубликован в репозитории Surf. Информацию по нему можно найти здесь https://bitbucket.org/surfstudio/android-standard , модуль easyadapter
